export const siteConfig = {
  name: "Beauty By Krimse",
  shortName: "Beauty By Krimse",
  tagline: "Luxury Hair & Makeup Artist",
  subheading: "Luxury Hair & Makeup Services for Weddings, Special Events, Photoshoots & Celebrations",
  supportingText: "Timeless, elevated beauty tailored to your unique vision.",
  email: "info@beautybykrimse.com",
  instagram: "https://instagram.com/beautybykrimse",
  instagramHandle: "@beautybykrimse",
  serviceArea: "Canada, GTA & Beyond (Destination Events)",
  whatsappNumber: "14379876427",
  displayPhone: "+1 (437) 987-6427",
  googleReviewUrl:
    process.env.NEXT_PUBLIC_GOOGLE_REVIEW_URL ||
    "https://www.google.com/search?hl=en-IN&gl=in&q=Beauty+By+Krimse,+33+University+Ave,+Toronto,+ON+M5J+2S7,+Canada&ludocid=1235993586447773071&lsig=AB86z5ULn1qWRLMoB9lqGPVyCTLA#lrd=0x89d4d323d79786f1:0x1127219e48e16d8f,3",
};

export const heroMedia = {
  primaryImage: "/mainimages/IMG_7657.jpg",
  secondaryImage: "/mainimages/IMG_7314.jpg",
};

export const trustPoints = [
  "5-Star Client Experience",
  "Toronto & GTA Mobile Services",
  "South Asian & Western Bridal Expertise",
  "Premium Products",
  "Team Available for Larger Bookings",
  "Client Reviews",
];

export const meetKrimse = {
  heading: "Meet Your Artist",
  subheading: "Hi, I'm Krimse.",
  body: "I specialize in creating timeless, elevated hair and makeup looks that enhance natural beauty while ensuring clients feel confident and comfortable.",
  image: "/IMG_6670.jpg",
};

export const featuredBridesGallery = [
  {
    id: "fb-1",
    title: "South Asian Brides",
    category: "South Asian Brides",
    image: "/mainimages/A8D59D07-30DA-4F20-A79E-0904251ACDAE.jpg",
    aspect: "portrait",
    caption: "Traditional South Asian bridal artistry featuring kundan placement and luminous skin.",
  },
  {
    id: "fb-2",
    title: "Western Brides",
    category: "Western Brides",
    image: "/mainimages/5FA19894-1C95-4D3C-AEB4-58D8AFBFAE4A.jpg",
    aspect: "landscape",
    caption: "Timeless Western bridal elegance with dewy radiant complexion and soft waves.",
  },
  {
    id: "fb-3",
    title: "Reception Glam",
    category: "Reception Glam",
    image: "/mainimages/IMG_6897.jpg",
    aspect: "portrait",
    caption: "High-fashion evening glam designed for celebration and dance floor longevity.",
  },
  {
    id: "fb-4",
    title: "Engagement Glam",
    category: "Engagement Glam",
    image: "/mainimages/IMG_6893.jpg",
    aspect: "portrait",
    caption: "Vibrant rose gold shimmer and romantic textured styling for pre-wedding celebrations.",
  },
  {
    id: "fb-5",
    title: "Bridal Party Looks",
    category: "Bridal Party Looks",
    image: "/mainimages/07A02717-D5C4-4459-8687-3341A6D9CB72.jpg",
    aspect: "landscape",
    caption: "Cohesive, radiant group hair and makeup coordinated for the entire bridal party.",
  },
  {
    id: "fb-6",
    title: "Timeless Bridal Moments",
    category: "South Asian Brides",
    image: "/mainimages/IMG_3497.jpg",
    aspect: "portrait",
    caption: "Flawless photography-ready finish engineered for outdoor ceremonies and natural light.",
  },
];

export const services = [
  {
    id: "bridal-hair-makeup",
    number: "01",
    title: "Bridal Hair & Makeup",
    description: "For your wedding day.",
    featuredImage: "/mainimages/IMG_7661.jpg",
    gallery: [
      "/mainimages/IMG_1303.jpg",
      "/mainimages/IMG_2466.jpg",
      "/mainimages/IMG_1590.jpg",
    ],
    bullets: [
      "Hair Styling",
      "Luxury Makeup Application",
      "Skin Preparation",
      "Lashes Included",
      "Dupatta / Veil Setting",
      "Jewelry Assistance",
      "Touch-Up Kit",
    ],
  },
  {
    id: "semi-bridal-hair-makeup",
    number: "02",
    title: "Semi-Bridal Hair & Makeup",
    description: "Perfect for engagement parties, sangeets, showers and special events.",
    featuredImage: "/mainimages/IMG_6895.jpg",
    gallery: [
      "/mainimages/IMG_5358.jpg",
      "/mainimages/IMG_6901.jpg",
      "/mainimages/IMG_1619.png",
    ],
    bullets: [
      "Hair Styling",
      "Makeup Application",
      "Skin Preparation",
      "Lashes Included",
      "Light Jewelry Assistance",
    ],
  },
  {
    id: "non-bridal-hair-makeup",
    number: "03",
    title: "Non-Bridal Hair & Makeup",
    description: "Soft glam for guests, family members, corporate events and celebrations.",
    featuredImage: "/mainimages/32B5FC26-913F-40F3-B783-50B0FF5A585F.jpg",
    gallery: [
      "/mainimages/IMG_1135.png",
      "/mainimages/IMG_1266.png",
      "/mainimages/IMG_1640.png",
    ],
    bullets: [
      "Hair Styling",
      "Makeup Application",
      "Skin Preparation",
      "Lashes Included",
    ],
  },
  {
    id: "bridal-party-services",
    number: "04",
    title: "Bridal Party Services",
    description: "Hair & makeup services for bridesmaids, mothers and wedding guests.",
    featuredImage: "/mainimages/4C53E8BE-3FEB-4DCC-B288-C89C02CD6EF5.jpg",
    gallery: [
      "/mainimages/IMG_7144.jpg",
      "/mainimages/IMG_7359.jpg",
      "/mainimages/IMG_1639.png",
    ],
    bullets: [
      "Individual Services",
      "Large Group Bookings",
      "Multiple Artists Available",
    ],
  },
];

export const serviceDropdownOptions = [
  { id: "south-asian-bridal", label: "South Asian Bridal Hair & Makeup" },
  { id: "western-bridal", label: "Western Bridal Hair & Makeup" },
  { id: "semi-bridal", label: "Semi-Bridal Hair & Makeup" },
  { id: "non-bridal", label: "Non-Bridal Hair & Makeup" },
  { id: "bridal-party", label: "Bridal Party Services" },
  { id: "makeup-only", label: "Makeup Only" },
  { id: "hair-only", label: "Hair Only" },
  { id: "trial-appointment", label: "Trial Appointment" },
];

export const whyBookWithUs = [
  "Luxury Hair & Makeup Services",
  "Toronto & GTA Mobile Services",
  "South Asian & Western Expertise",
  "Premium Products",
  "Team Available for Larger Bookings",
  "5-Star Client Experience",
];

export const serviceAreas = {
  heading: "Where We Travel",
  items: [
    {
      title: "Toronto & GTA",
      desc: "Mobile services throughout the Greater Toronto Area.",
    },
    {
      title: "Across Canada",
      desc: "Travel available across Canada.",
    },
    {
      title: "Destination Events",
      desc: "Available for destination weddings and special events.",
    },
  ],
};

export const videos = [
  {
    id: "vid-1",
    title: "Bridal Artistry & Detail",
    subtitle: "Behind the Artistry",
    src: "/mainimages/IMG_6637.mp4",
    poster: "/mainimages/IMG_7613.jpg",
    description: "Signature bridal transformation showcasing delicate skin radiance and royal jewelry placement.",
  },
  {
    id: "vid-2",
    title: "Bridal Radiance in Motion",
    subtitle: "Cinematic Glow",
    src: "/mainimages/IMG_7806.mp4",
    poster: "/mainimages/IMG_7792.jpg",
    description: "Luminous complexion work that moves naturally under 4K camera lenses and outdoor sunlight.",
  },
  {
    id: "vid-3",
    title: "Dupatta Drapery & Crown Styling",
    subtitle: "Precision Styling",
    src: "/mainimages/IMG_2318.mp4",
    poster: "/mainimages/IMG_7788.jpg",
    description: "Meticulous dupatta setting and crown pinning engineered for comfort and all-day stability.",
  },
  {
    id: "vid-4",
    title: "Celebration & Movement",
    subtitle: "Event Ready",
    src: "/mainimages/IMG_2333.mp4",
    poster: "/mainimages/IMG_6900.jpg",
    description: "Dynamic pre-wedding glam and waves crafted to stay flawless through hours of celebration.",
  },
];

export const perfectLook = {
  heading: "Say Yes to the Perfect Look",
  body: "From weddings and special events to editorial shoots and everyday glamour, Beauty By Krimse is your trusted partner for achieving unparalleled elegance and confidence through makeup artistry. Elevate your beauty experience with Krimse – where professionalism meets perfection. Schedule your consultation today to embark on a journey of timeless beauty and sophistication.",
  primaryCta: {
    label: "Discover More",
    href: "/portfolio",
  },
  secondaryCta: {
    label: "Schedule Consultation",
    href: "/inquire",
  },
};

export const faqList = [
  {
    question: "Do you travel to my location?",
    answer: "Yes, we provide on-location mobile services throughout Toronto & the GTA, across Canada, and for destination events worldwide.",
  },
  {
    question: "Do you offer trials?",
    answer: "Yes, bridal trial appointments are available to preview and customize your hair and makeup vision ahead of your wedding day.",
  },
  {
    question: "Do you accommodate large bridal parties?",
    answer: "Yes, we have a qualified team available to accommodate large bridal parties and group bookings with organized timelines.",
  },
  {
    question: "Do you schedule consultation calls?",
    answer: "Yes, we are happy to schedule a consultation to discuss your event timeline, vision, and custom services.",
  },
  {
    question: "How quickly will I receive a response?",
    answer: "We review all inquiries promptly and will get back to you within 24–48 hours.",
  },
];

export const portfolioCategories = [
  { id: "all", name: "All Works" },
  { id: "south-asian-brides", name: "South Asian Brides" },
  { id: "western-brides", name: "Western Brides" },
  { id: "reception-glam", name: "Reception Glam" },
  { id: "engagement-glam", name: "Engagement Glam" },
  { id: "bridal-party", name: "Bridal Party" },
];

export const portfolioItems = [
  {
    id: "port-1",
    title: "Regal Bridal Portraiture",
    category: "south-asian-brides",
    categoryName: "South Asian Brides",
    image: "/mainimages/IMG_6670.jpg",
    aspect: "portrait",
    caption: "Traditional South Asian bridal artistry with kundan placement and flawless skin sculpting.",
  },
  {
    id: "port-2",
    title: "Intricate Mathapatti & Polki Choker",
    category: "south-asian-brides",
    categoryName: "South Asian Brides",
    image: "/mainimages/IMG_6671.jpg",
    aspect: "portrait",
    caption: "Close-up detailing heirloom bridal jewelry anchoring and winged eye precision.",
  },
  {
    id: "port-3",
    title: "Velvet Soft-Glam Complexion",
    category: "south-asian-brides",
    categoryName: "South Asian Brides",
    image: "/mainimages/IMG_6684.jpg",
    aspect: "portrait",
    caption: "Weightless skin blending and soft contouring tailored for 4K photography.",
  },
  {
    id: "port-4",
    title: "Bridal Profile & Winged Liner",
    category: "south-asian-brides",
    categoryName: "South Asian Brides",
    image: "/mainimages/IMG_6690.jpg",
    aspect: "portrait",
    caption: "Focused eye artistry with fluttery lashes and sculpted brow design.",
  },
  {
    id: "port-5",
    title: "Couture Dupatta Anchoring",
    category: "south-asian-brides",
    categoryName: "South Asian Brides",
    image: "/mainimages/IMG_6693.jpg",
    aspect: "portrait",
    caption: "Secure dupatta pleating and crown pinning engineered for all-day comfort.",
  },
  {
    id: "port-6",
    title: "Textured Bridal Updo",
    category: "western-brides",
    categoryName: "Western Brides",
    image: "/mainimages/IMG_7782.jpg",
    aspect: "portrait",
    caption: "Dimensional hair architecture with soft face-framing tendrils and veil integration.",
  },
  {
    id: "port-7",
    title: "Sculpted Bridal Bun",
    category: "western-brides",
    categoryName: "Western Brides",
    image: "/mainimages/IMG_7790.jpg",
    aspect: "portrait",
    caption: "Clean, elegant bridal hair styling designed for veil anchoring and movement.",
  },
  {
    id: "port-8",
    title: "Radiant Morning Bridal Glow",
    category: "south-asian-brides",
    categoryName: "South Asian Brides",
    image: "/mainimages/IMG_7978.jpg",
    aspect: "portrait",
    caption: "Fresh luminous complexion and soft rose nude lip artistry.",
  },
  {
    id: "port-9",
    title: "Glass-Skin Bridal Radiance",
    category: "south-asian-brides",
    categoryName: "South Asian Brides",
    image: "/mainimages/IMG_7979.jpg",
    aspect: "portrait",
    caption: "Seamless foundation match and radiant skin barrier preparation.",
  },
  {
    id: "port-10",
    title: "Golden Shimmer Eye Artistry",
    category: "engagement-glam",
    categoryName: "Engagement Glam",
    image: "/mainimages/IMG_7987.jpg",
    aspect: "portrait",
    caption: "Dimensional golden eyes with precision liner and custom mink lashes.",
  },
  {
    id: "port-11",
    title: "Champagne Glow & Statement Jewels",
    category: "south-asian-brides",
    categoryName: "South Asian Brides",
    image: "/mainimages/IMG_7989.jpg",
    aspect: "portrait",
    caption: "Harmonious balance of regal jewelry and luminous, breathable makeup.",
  },
  {
    id: "port-12",
    title: "Regal Crimson Bridal Suite",
    category: "south-asian-brides",
    categoryName: "South Asian Brides",
    image: "/mainimages/IMG_7991.jpg",
    aspect: "portrait",
    caption: "Traditional crimson lehenga styling with emerald polki jewelry and soft glam.",
  },
  {
    id: "port-13",
    title: "Old Hollywood Bridal Waves",
    category: "western-brides",
    categoryName: "Western Brides",
    image: "/mainimages/IMG_9123.jpg",
    aspect: "portrait",
    caption: "High-gloss Old Hollywood waves with structural wave definition and mirror shine.",
  },
  {
    id: "port-14",
    title: "Sangeet Night Glamour",
    category: "engagement-glam",
    categoryName: "Engagement Glam",
    image: "/mainimages/IMG_9614.jpg",
    aspect: "portrait",
    caption: "Vibrant eye artistry and high-movement waves for pre-wedding celebrations.",
  },
  {
    id: "port-15",
    title: "Cocktail Celebration Look",
    category: "reception-glam",
    categoryName: "Reception Glam",
    image: "/mainimages/IMG_9615.jpg",
    aspect: "portrait",
    caption: "Sultry evening beauty tailored for dinner, toasts, and dancing.",
  },
  {
    id: "port-16",
    title: "Modern Reception Elegance",
    category: "reception-glam",
    categoryName: "Reception Glam",
    image: "/mainimages/IMG_9921.jpg",
    aspect: "portrait",
    caption: "Editorial evening glam featuring dimensional contouring and defined lashes.",
  },
  {
    id: "port-17",
    title: "Sacred Ceremony Portrait",
    category: "south-asian-brides",
    categoryName: "South Asian Brides",
    image: "/mainimages/IMG_3491.jpg",
    aspect: "portrait",
    caption: "Emotion-proof, sweat-resistant bridal artistry through religious ceremonies.",
  },
  {
    id: "port-18",
    title: "Sunlit Bridal Elegance",
    category: "south-asian-brides",
    categoryName: "South Asian Brides",
    image: "/mainimages/IMG_3495.jpg",
    aspect: "portrait",
    caption: "Natural daylight highlighting flawless skin texture and kundan jewelry.",
  },
  {
    id: "port-19",
    title: "Joyful Wedding Couple",
    category: "south-asian-brides",
    categoryName: "South Asian Brides",
    image: "/mainimages/IMG_3496.jpg",
    aspect: "portrait",
    caption: "Timeless wedding couple portrait with all-day longwear beauty.",
  },
  {
    id: "port-20",
    title: "Radiant Bride in Suite",
    category: "south-asian-brides",
    categoryName: "South Asian Brides",
    image: "/mainimages/IMG_1614.jpg",
    aspect: "portrait",
    caption: "Serene morning moments in the bridal suite with peaceful ambiance.",
  },
  {
    id: "port-21",
    title: "Dupatta Pleating & Mathapatti",
    category: "south-asian-brides",
    categoryName: "South Asian Brides",
    image: "/mainimages/IMG_1615.jpg",
    aspect: "portrait",
    caption: "Structural pinning ensuring immovable dupatta placement for 16+ hours.",
  },
  {
    id: "port-22",
    title: "Traditional Crimson Grandeur",
    category: "south-asian-brides",
    categoryName: "South Asian Brides",
    image: "/mainimages/IMG_1618.jpg",
    aspect: "portrait",
    caption: "Bespoke bridal look honoring cultural heritage and personal elegance.",
  },
  {
    id: "port-23",
    title: "Editorial Bridal Close-Up",
    category: "western-brides",
    categoryName: "Western Brides",
    image: "/mainimages/23ECEA9D-C0A8-4517-8274-801CA1BD003C.jpg",
    aspect: "portrait",
    caption: "Clean, minimalist beauty focusing on luminous skin and subtle definition.",
  },
  {
    id: "port-24",
    title: "Flawless Bridal Eye Detailing",
    category: "south-asian-brides",
    categoryName: "South Asian Brides",
    image: "/mainimages/24369B4D-0152-49D3-96B9-4540C7029359.jpg",
    aspect: "portrait",
    caption: "Custom lash mapping and softly blended eyeshadow contours.",
  },
  {
    id: "port-25",
    title: "Evening Gala Radiance",
    category: "reception-glam",
    categoryName: "Reception Glam",
    image: "/mainimages/3692F341-7746-40D4-889E-8425E4C28A90.jpg",
    aspect: "portrait",
    caption: "Refined evening makeup designed for dim candlelit receptions and flash photography.",
  },
  {
    id: "port-26",
    title: "Modern Minimalist Bride",
    category: "western-brides",
    categoryName: "Western Brides",
    image: "/mainimages/50EDBCCF-CA03-4A7B-8313-7C5D79A26E47.jpg",
    aspect: "portrait",
    caption: "Fresh, effortless bridal look with natural dewy skin and fluttery lashes.",
  },
  {
    id: "port-27",
    title: "Bridal Party Morning Celebration",
    category: "bridal-party",
    categoryName: "Bridal Party",
    image: "/mainimages/6C97FAFC-1D46-4443-A55C-AF1E41B96391.jpg",
    aspect: "landscape",
    caption: "Harmonious, glowing makeup for bridesmaids and mothers of the bride.",
  },
  {
    id: "port-28",
    title: "Reception Glamour",
    category: "reception-glam",
    categoryName: "Reception Glam",
    image: "/mainimages/736D5BCC-8384-4AF5-B57D-853BC2F3788F.jpg",
    aspect: "portrait",
    caption: "Dramatic lash volume and luminous cheekbones for evening reception.",
  },
  {
    id: "port-29",
    title: "Pre-Wedding Celebration Glam",
    category: "engagement-glam",
    categoryName: "Engagement Glam",
    image: "/mainimages/8021F2E8-BFC4-46E8-B2BD-CFB54131EA6C.jpg",
    aspect: "portrait",
    caption: "Playful colors and radiant skin for pre-wedding festivities.",
  },
  {
    id: "port-30",
    title: "Cocktail Night Elegance",
    category: "reception-glam",
    categoryName: "Reception Glam",
    image: "/mainimages/8F9A0309-E710-4DBD-8492-E850CC71DB17.jpg",
    aspect: "portrait",
    caption: "Sleek, sophisticated event makeup with luminous undertones.",
  },
  {
    id: "port-31",
    title: "Luminous Bridal Complexion",
    category: "south-asian-brides",
    categoryName: "South Asian Brides",
    image: "/mainimages/AF73F5A0-ADF3-44B4-86ED-B69550CCDA3C.jpg",
    aspect: "portrait",
    caption: "Seamless blending that photographs flawlessly under 4K lenses.",
  },
  {
    id: "port-32",
    title: "Soft Elegance & Polki Accents",
    category: "south-asian-brides",
    categoryName: "South Asian Brides",
    image: "/mainimages/B959167E-B8D3-4CE2-91BF-F1BFE24D1FC1.jpg",
    aspect: "portrait",
    caption: "Balanced traditional jewelry placement and soft glam contouring.",
  },
  {
    id: "port-33",
    title: "Mehendi Night Artistry",
    category: "engagement-glam",
    categoryName: "Engagement Glam",
    image: "/mainimages/B9D5CB44-7EE3-44A5-A5BE-83ED9E44B14A.jpg",
    aspect: "portrait",
    caption: "Bright, radiant skin with soft waves for lively celebration nights.",
  },
  {
    id: "port-34",
    title: "Classic Western Bridal Glow",
    category: "western-brides",
    categoryName: "Western Brides",
    image: "/mainimages/C9908057-4D24-4388-9D3E-392FC8977C7B.jpg",
    aspect: "portrait",
    caption: "Timeless bridal glow with natural lash definition and veil finish.",
  },
];

export const reviewMakeupImageMap = {
  "Sargam": "/reviewimages/sargam.png",
  "Janushi": "/reviewimages/janushi.png",
  "Sapriya": "/reviewimages/sapriya.png",
  "Madhumita": "/reviewimages/Madhumita.png",
  "Preeti": "/reviewimages/Preeti.png",
  "Raajvi": "/reviewimages/Raajvi.png",
  "Rajvi Nayak": "/reviewimages/RajviNayak.png",
};

export const loveNotes = [
  {
    id: "g-rev-1",
    authorName: "Sargam",
    role: "Bride & Mom",
    location: "Burlington, Ontario",
    reviewText: "Hi cutie, I wanted to thank you for making me look extra beautiful on each day, every look was so different but still felt like me! And most importantly you made my mom feel beautiful, I couldn’t have asked for a bigger blessing that she was happy!! I’m so glad I trusted you with the most important week of my life! ♥️♥️♥️",
    rating: 5,
    profilePhoto: null,
    makeupImage: "/reviewimages/sargam.png",
    relativeTime: "Google Review",
    source: "Google",
    googleReviewUrl: siteConfig.googleReviewUrl,
  },
  {
    id: "g-rev-2",
    authorName: "Janushi",
    role: "Gujarati Bride",
    location: "Caledon, Ontario",
    reviewText: "Thank you so so much Krimse for everything!! I felt so beautiful and looked like myself too!! You’re the best!!!!",
    rating: 5,
    profilePhoto: null,
    makeupImage: "/reviewimages/janushi.png",
    relativeTime: "Google Review",
    source: "Google",
    googleReviewUrl: siteConfig.googleReviewUrl,
  },
  {
    id: "g-rev-3",
    authorName: "Sapriya",
    role: "Anand Karaj Bride",
    location: "London, ON",
    reviewText: "Krimse did my bridal hair and makeup as well as my bridal party. She did a fantastic job. We were all so thrilled with how we looked. I would highly recommend her services, she was so lovely to work with!",
    rating: 5,
    profilePhoto: null,
    makeupImage: "/reviewimages/sapriya.png",
    relativeTime: "Google Review",
    source: "Google",
    googleReviewUrl: siteConfig.googleReviewUrl,
  },
  {
    id: "g-rev-4",
    authorName: "Madhumita",
    role: "South Indian Bride",
    location: "Scarborough, ON",
    reviewText: "I'm so glad Krimse did my makeup for my wedding and reception!! She's so kind and patient, and I got so many compliments on my look!",
    rating: 5,
    profilePhoto: null,
    makeupImage: "/reviewimages/Madhumita.png",
    relativeTime: "Google Review",
    source: "Google",
    googleReviewUrl: siteConfig.googleReviewUrl,
  },
  {
    id: "g-rev-5",
    authorName: "Preeti",
    role: "Bride + Bridal Party (Western and Indian Wedding)",
    location: "Brampton, ON",
    reviewText: "Krimse was amazing to work with! She was very friendly, responsive, professional, open to feedback, and gave great suggestions for my bridal hair and makeup. She was also very accommodating when I had to change my getting-ready location at the last minute. She took the time to ensure the perfect bridal look for my Hindu and Christian weddings, and with my skin type, also made sure it lasted the whole day (and it did!). I received many compliments from friends, family, and of course my husband!\n\nI highly recommend her bridal and non-bridal services, and will definitely consider her for future events.",
    rating: 5,
    profilePhoto: null,
    makeupImage: "/reviewimages/Preeti.png",
    relativeTime: "Google Review",
    source: "Google",
    googleReviewUrl: siteConfig.googleReviewUrl,
  },
  {
    id: "g-rev-6",
    authorName: "Raajvi",
    role: "Gujarati Wedding Bride",
    location: "Newmarket, ON",
    reviewText: "It was an absolute pleasure working with Krimse and her team for my wedding and reception! Krimse understood my vision for both the events and the final looks were better than my expectations! I also booked her team for my bridal party and everyone in my bridal party loved their makeup and hair! I would definitely book her again for future events!",
    rating: 5,
    profilePhoto: null,
    makeupImage: "/reviewimages/Raajvi.png",
    relativeTime: "Google Review",
    source: "Google",
    googleReviewUrl: siteConfig.googleReviewUrl,
  },
  {
    id: "g-rev-7",
    authorName: "Rajvi Nayak",
    role: "Special Event Glam",
    location: "Ontario",
    reviewText: "I can’t recommend Krimse enough! She did both my mom’s and my makeup for my special event, and we were both beyond happy with the results. She took the time to understand exactly what each of us wanted and created looks that suited us perfectly. Our makeup looked absolutely flawless, lasted all day. We received so many compliments throughout the event! She is incredibly talented, she’s so kind, professional, and made the whole experience so enjoyable. If you’re looking for a makeup artist who truly cares about her clients and delivers amazing results, Krimse is the one. We will definitely be booking with her again! 🥰✨",
    rating: 5,
    profilePhoto: null,
    makeupImage: "/reviewimages/RajviNayak.png",
    relativeTime: "Google Review",
    source: "Google",
    googleReviewUrl: siteConfig.googleReviewUrl,
  },
  {
    id: "g-rev-8",
    authorName: "Ritika",
    role: "Wedding Bride & Bridal Party",
    location: "Ontario",
    reviewText: "I can’t thank Krimse enough for the incredible job she did on my wedding day! She is so sweet, kind, and was genuinely attentive to my vision. She took the time to really understand the kind of bridal look I wanted—and delivered it so beautifully. I felt like the best version of myself, and my makeup lasted all day flawlessly.\n\nNot only did she create my dream bridal look, but she also worked her magic on my mother, mother-in-law, groom, and groomsmen. Everyone looked polished and glowing without being overdone—just perfect for the occasion. She made us all feel so comfortable and at ease during the process, which was such a gift on a busy and emotional day.\n\nKrimse is truly talented, professional, and has the warmest presence. I’m so grateful she was a part of my wedding. Highly, highly recommend her to any bride or bridal party looking for someone who listens, cares, and delivers stunning results. Thank you, Krimse!",
    rating: 5,
    profilePhoto: null,
    makeupImage: null,
    relativeTime: "Google Review",
    source: "Google",
    googleReviewUrl: siteConfig.googleReviewUrl,
  },
];

// Alias for backwards compatibility
export const clientReviews = loveNotes;
